name: Weekly Pre-commit

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * MON"

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Node dependencies
        run: npm install --no-package-lock

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
